init:
  home: "./network/data/refund"
build:
  main: "./app"
accounts:
  - name: alice
    coins: ["2000000000000000ufetf"]
    mnemonic: "alley afraid soup fall idea toss can goose become valve initial strong forward bright dish figure check leopard decide warfare hub unusual join cart"
  - name: bob
    coins: ["100000000000000000ufetf"]
    mnemonic: "alpha crisp zoo letter pepper subway crew drum illegal powder input shuffle team east village nurse captain mule token ice drive act boy punch"
  - name: faucet
    coins: ["50000000000000ufetf",]
    mnemonic: "bomb choose medal limb place hip axis pave reject rack recipe cover family vivid humble kingdom exhibit limit snow biology special swing emotion call"
validator:
  name: alice
  staked: "100000000ufetf"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: faucet
  coins: ["50000000000000ufetf"]
genesis:
  chain_id: "refund"
  app_state:
    staking:
      params:
        bond_denom: "ufetf"
    mint:
      params:
        mint_denom: "ufetf"
    crisis:
      constant_fee:
        denom: "ufetf"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "ufetf"
    broker:
      brokers:
